import React from 'react';
import { FileText, Download, Eye } from 'lucide-react';

export default function RecentReports() {
  const dummyData = [
    { id: 1, name: 'Monthly Attendance - July', category: 'Attendance', by: 'John Doe', on: '2026-08-01', format: 'PDF', status: 'Completed' },
    { id: 2, name: 'Q2 Payroll Register', category: 'Payroll', by: 'Jane Smith', on: '2026-07-28', format: 'Excel', status: 'Completed' },
    { id: 3, name: 'Leave Balance Report', category: 'Leave', by: 'John Doe', on: '2026-07-25', format: 'CSV', status: 'Failed' },
    { id: 4, name: 'Active Employees Directory', category: 'Employees', by: 'Admin User', on: '2026-07-20', format: 'PDF', status: 'Completed' },
  ];

  return (
    <div className="bg-white rounded-xl border border-[#d6d9df] overflow-hidden">
      <div className="px-5 py-4 border-b border-[#d6d9df] bg-slate-50 flex items-center justify-between">
        <h3 className="font-bold text-slate-800 flex items-center gap-2">
          <FileText size={18} className="text-slate-500" />
          Recent Generated Reports
        </h3>
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-white text-xs text-slate-500 border-b border-[#d6d9df]">
              <th className="px-5 py-3 font-semibold">Report Name</th>
              <th className="px-5 py-3 font-semibold">Category</th>
              <th className="px-5 py-3 font-semibold">Generated By</th>
              <th className="px-5 py-3 font-semibold">Generated On</th>
              <th className="px-5 py-3 font-semibold">Status</th>
              <th className="px-5 py-3 font-semibold text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="text-sm">
            {dummyData.map((report) => (
              <tr key={report.id} className="border-b border-slate-100 hover:bg-slate-50 transition-colors">
                <td className="px-5 py-3 font-medium text-slate-800 flex items-center gap-2">
                  {report.format === 'PDF' ? (
                    <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-red-100 text-red-600">PDF</span>
                  ) : report.format === 'Excel' ? (
                    <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-green-100 text-green-600">XLSX</span>
                  ) : (
                    <span className="px-1.5 py-0.5 rounded text-[10px] font-bold bg-blue-100 text-blue-600">CSV</span>
                  )}
                  {report.name}
                </td>
                <td className="px-5 py-3 text-slate-600">{report.category}</td>
                <td className="px-5 py-3 text-slate-600">{report.by}</td>
                <td className="px-5 py-3 text-slate-600">{report.on}</td>
                <td className="px-5 py-3">
                  <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${
                    report.status === 'Completed' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'
                  }`}>
                    {report.status}
                  </span>
                </td>
                <td className="px-5 py-3 text-right">
                  <div className="flex items-center justify-end gap-2">
                    <button className="p-1.5 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors" title="View">
                      <Eye size={16} />
                    </button>
                    <button className="p-1.5 text-slate-400 hover:text-blue-600 hover:bg-blue-50 rounded transition-colors" title="Download">
                      <Download size={16} />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
