const PDFDocument = require('pdfkit');

/**
 * Generates a generic PDF buffer from standard report JSON.
 *
 * @param {Object} reportJson - Standardized report JSON
 * @param {Object} companyInfo - Company configuration object
 * @returns {Promise<Buffer>} Resolves to PDF file buffer
 */
const generatePdf = (reportJson, companyInfo) => {
    return new Promise((resolve, reject) => {
        try {
            const { title, subtitle, generatedAt, generatedBy, filters, summary, columns = [], rows = [] } = reportJson;

            // Create a document with landscape orientation for better table fitting
            const doc = new PDFDocument({ margin: 30, size: 'A4', layout: 'landscape' });
            
            const buffers = [];
            doc.on('data', buffers.push.bind(buffers));
            doc.on('end', () => {
                const pdfData = Buffer.concat(buffers);
                resolve(pdfData);
            });

            // --- Header & Branding ---
            if (companyInfo) {
                // If logo exists locally or accessible URL, we could fetch it here.
                // For this generic setup, we'll just print the company name prominently.
                doc.fontSize(20).font('Helvetica-Bold').text(companyInfo.companyName || 'Company Report', { align: 'center' });
                
                const addressParts = [companyInfo.addressLine1, companyInfo.city, companyInfo.state, companyInfo.zipCode].filter(Boolean).join(', ');
                if (addressParts) {
                    doc.fontSize(10).font('Helvetica').text(addressParts, { align: 'center' });
                }
                const contactParts = [companyInfo.officialEmail, companyInfo.phone].filter(Boolean).join(' | ');
                if (contactParts) {
                    doc.fontSize(10).font('Helvetica').text(contactParts, { align: 'center' });
                }
                doc.moveDown(1.5);
            }

            // --- Report Metadata ---
            doc.fontSize(16).font('Helvetica-Bold').text(title || 'Report');
            if (subtitle) {
                doc.fontSize(12).font('Helvetica').text(subtitle);
            }
            doc.fontSize(10).font('Helvetica').text(`Generated On: ${new Date(generatedAt).toLocaleString()}`);
            doc.text(`Generated By: ${generatedBy}`);
            doc.moveDown(1);

            // --- Summary Section ---
            if (summary && Object.keys(summary).length > 0) {
                doc.fontSize(12).font('Helvetica-Bold').text('Summary:');
                doc.fontSize(10).font('Helvetica');
                Object.entries(summary).forEach(([k, v]) => {
                    doc.text(`${k}: ${v}`);
                });
                doc.moveDown(1);
            }

            // --- Main Table Drawing (Simple Implementation) ---
            if (columns.length > 0) {
                const usableWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
                const colWidth = usableWidth / columns.length;
                let startY = doc.y;
                
                // Dynamic font scaling for many columns
                const headerFontSize = columns.length > 15 ? 6 : columns.length > 8 ? 7 : 9;
                const rowFontSize = columns.length > 15 ? 5 : columns.length > 8 ? 6 : 8;

                // Function to check page overflow
                const checkNewPage = (heightNeeded) => {
                    if (doc.y + heightNeeded > doc.page.height - doc.page.margins.bottom) {
                        doc.addPage();
                        startY = doc.y || doc.page.margins.top;
                        return true;
                    }
                    return false;
                };

                // Draw Headers
                doc.font('Helvetica-Bold').fontSize(headerFontSize);
                columns.forEach((col, i) => {
                    doc.text(col, doc.page.margins.left + (i * colWidth), startY, { width: colWidth - 2, align: 'left' });
                });
                startY += (headerFontSize + 6);
                doc.moveTo(doc.page.margins.left, startY).lineTo(doc.page.width - doc.page.margins.right, startY).stroke();
                startY += 5;

                // Draw Rows
                if (rows.length === 0) {
                    doc.font('Helvetica').fontSize(rowFontSize);
                    doc.text('No records found', doc.page.margins.left, startY, { align: 'center' });
                    startY += (rowFontSize + 7);
                } else {
                    doc.font('Helvetica').fontSize(rowFontSize);
                    rows.forEach(row => {
                        // Estimate row height based on font size
                        const rowHeight = rowFontSize + 7; 
                        if (checkNewPage(rowHeight)) {
                            startY = doc.y + 10;
                        }

                        row.forEach((cell, i) => {
                            const cellText = (cell === null || cell === undefined) ? '' : String(cell);
                            doc.text(cellText, doc.page.margins.left + (i * colWidth), startY, { width: colWidth - 2, align: 'left', lineBreak: false });
                        });
                        startY += rowHeight;
                    });
                }
            }

            // --- Pagination Footer ---
            let pages = doc.bufferedPageRange();
            for (let i = 0; i < pages.count; i++) {
                doc.switchToPage(i);
                doc.fontSize(8).text(`Page ${i + 1} of ${pages.count}`, doc.page.margins.left, doc.page.height - 20, { align: 'center' });
            }

            doc.end();
        } catch (error) {
            reject(error);
        }
    });
};

module.exports = { generatePdf };
