const XLSX = require('xlsx');

/**
 * Generates a generic Excel (XLSX) buffer from standard report JSON.
 *
 * @param {Object} reportJson - Standardized report JSON
 * @param {Object} companyInfo - Company configuration object
 * @returns {Buffer} XLSX file buffer
 */
const generateExcel = (reportJson, companyInfo) => {
    const { title, subtitle, generatedAt, generatedBy, filters, summary, columns = [], rows = [] } = reportJson;

    // Build the worksheet data as an array of arrays
    const wsData = [];

    // --- 1. Company Branding Header ---
    if (companyInfo) {
        wsData.push([companyInfo.companyName || '']);
        const addressParts = [companyInfo.addressLine1, companyInfo.city, companyInfo.state, companyInfo.zipCode].filter(Boolean).join(', ');
        if (addressParts) wsData.push([addressParts]);
        
        const contactParts = [companyInfo.officialEmail, companyInfo.phone].filter(Boolean).join(' | ');
        if (contactParts) wsData.push([contactParts]);
        wsData.push([]); // Empty row separator
    }

    // --- 2. Report Metadata ---
    wsData.push([title || 'Report']);
    if (subtitle) wsData.push([subtitle]);
    wsData.push([`Generated On: ${new Date(generatedAt).toLocaleString()}`]);
    wsData.push([`Generated By: ${generatedBy}`]);
    wsData.push([]); // Empty row separator

    // --- 3. Filters Section ---
    if (filters && Object.keys(filters).length > 0) {
        wsData.push(['Applied Filters:']);
        Object.entries(filters).forEach(([k, v]) => {
            // Flatten simple objects for display
            const val = typeof v === 'object' ? JSON.stringify(v) : v;
            wsData.push([k, val]);
        });
        wsData.push([]);
    }

    // --- 4. Summary Section ---
    if (summary && Object.keys(summary).length > 0) {
        wsData.push(['Summary:']);
        Object.entries(summary).forEach(([k, v]) => {
            wsData.push([k, v]);
        });
        wsData.push([]);
    }

    // --- 5. Main Data Table ---
    wsData.push(columns); // Header row
    
    if (rows.length === 0) {
        wsData.push(['No records found']);
    } else {
        rows.forEach(row => {
            // Process cells to convert currency strings to numbers and recognize dates
            const processedRow = row.map(cell => {
                if (typeof cell === 'string') {
                    // Check if it's a currency string like ₹5,000
                    if (cell.startsWith('₹')) {
                        const numStr = cell.replace(/[₹,]/g, '').trim();
                        const num = Number(numStr);
                        if (!isNaN(num)) return num;
                    }
                    // Check if it's a date string (DD/MM/YYYY)
                    const dateMatch = cell.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
                    if (dateMatch) {
                        // Return Date object so XLSX can format it
                        return new Date(dateMatch[3], dateMatch[2] - 1, dateMatch[1]);
                    }
                }
                return cell;
            });
            wsData.push(processedRow);
        });
    }

    // Create workbook and worksheet
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(wsData);

    // Make headers bold (row 0 to 4 are metadata, columns header is dynamic)
    // To keep it simple, we don't manipulate the XLSX styles directly here as Community Edition doesn't support complex styling easily,
    // but the data types will be correct. (Pro version needed for true bolding, but dates/numbers are fixed).

    // Auto-size columns based on the data rows (simple heuristic)
    if (columns.length > 0) {
        const colWidths = columns.map((col, i) => {
            let maxLen = String(col).length;
            rows.forEach(row => {
                const val = String(row[i] || '');
                if (val.length > maxLen) maxLen = val.length;
            });
            // Cap max width to 50 characters to avoid absurdly wide columns
            return { wch: Math.min(maxLen + 2, 50) };
        });
        ws['!cols'] = colWidths;
    }

    XLSX.utils.book_append_sheet(wb, ws, "Report");

    // Write to buffer
    const buffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
    return buffer;
};

module.exports = { generateExcel };
